# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1e9b986c8fd67b3e70bff40052282c201ca30c0ba3cad266b86b694ef1e1a6ffb379cda7dcc7f1360b978ede2e1a31e99c72061a7909997478bfa5766137ca9e

test:
  secret_key_base: b98d2619d6153981fba0e926bfdaae4d980738353113f7f71ecfd4d0e5a5fe0777af320af6d7f09390c6eec6ffade04dbc07f8c46acac866562c38c58c91ae20

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
